/**
 * Every gateway surface the app can show, from the dashboard's own definition.
 *
 * GENERATED by scripts/gen-surface-catalog.mjs from
 * scripts/data/dashboard-surfaces.json — do not edit by hand. The snapshot is
 * derived from diegosouzapw/OmniRoute @ release/v3.8.52, and `npm run surfaces:test` fails if this
 * file and the snapshot disagree.
 *
 * `kind` is which native renderer draws the surface:
 *   custom     — a purpose-built screen, listed in APP_ROUTES below
 *   config     — a settings object: native toggles, fields and pickers
 *   collection — a list of records with search and a detail view
 *   stats      — numbers and breakdowns for a window of traffic
 *   local      — not gateway data; the screen explains why
 *   external   — a link out of the app, opened deliberately by the user
 */

import type { MaterialCommunityIcons } from '@expo/vector-icons';

export type SurfaceKind = 'custom' | 'config' | 'collection' | 'stats' | 'local' | 'external';

export interface Surface {
  /** Stable id, used in the route and as a list key. */
  id: string;
  title: string;
  subtitle: string;
  /** MaterialCommunityIcons name. */
  icon: keyof typeof MaterialCommunityIcons.glyphMap;
  /** Section title, as the dashboard groups them. */
  section: string;
  kind: SurfaceKind;
  /** API route the surface reads (and usually writes). */
  path?: string;
  /** How a config surface writes back, when the route takes one. */
  method?: 'patch' | 'post' | 'put';
  /** For custom surfaces: the expo-router route to open. */
  route?: string;
  /** For local surfaces: why there is nothing to fetch. */
  note?: string;
  /** The dashboard page this replaces, kept for traceability. */
  page?: string;
}

export interface SurfaceSection {
  id: string;
  /** The dashboard's own section name, kept for traceability. */
  title: string;
  /** What the phone menu shows — short, and not the internal taxonomy. */
  label: string;
  subtitle: string;
  icon: Surface['icon'];
  surfaces: Surface[];
}

/** Surfaces that get their own screen rather than a renderer. */
export const APP_ROUTES: Record<string, string> = {
  'api-manager': '/keys',
  'providers': '/(tabs)/providers',
  'model-catalog': '/(tabs)/models',
  'combos': '/combos',
  'logs': '/logs',
  'playground': '/(tabs)/chat',
  'settings-general': '/settings',
};

export const SURFACES: Surface[] = [
  // ── OmniProxy ──
  { id: 'endpoints', title: 'Endpoints', subtitle: 'Your AI connection URLs', icon: 'link-variant', section: 'OmniProxy', kind: 'config', path: '/api/settings', method: 'patch', page: '/dashboard/endpoint' },
  { id: 'api-manager', title: 'API Keys', subtitle: 'Manage API keys and access', icon: 'key-outline', section: 'OmniProxy', kind: 'custom', route: '/keys', page: '/dashboard/api-manager' },
  { id: 'providers', title: 'Providers', subtitle: '358 providers, one endpoint', icon: 'dns-outline', section: 'OmniProxy', kind: 'custom', route: '/(tabs)/providers', page: '/dashboard/providers' },
  { id: 'model-catalog', title: 'Model Catalog', subtitle: 'Browse models across providers', icon: 'format-list-bulleted', section: 'OmniProxy', kind: 'custom', route: '/(tabs)/models', page: '/dashboard/models' },
  { id: 'embedded-services', title: 'Embedded Services', subtitle: 'Optional local services', icon: 'server', section: 'OmniProxy', kind: 'collection', path: '/api/services/cliproxy/accounts', page: '/dashboard/providers/services' },
  { id: 'combos', title: 'Combos', subtitle: 'Group providers for failover', icon: 'layers-triple-outline', section: 'OmniProxy', kind: 'custom', route: '/combos', page: '/dashboard/combos' },
  { id: 'combos-live', title: 'Combo Studio', subtitle: 'Live routing cascade', icon: 'sitemap-outline', section: 'OmniProxy', kind: 'collection', path: '/api/monitoring/health', page: '/dashboard/combos/live' },
  { id: 'provider-quota', title: 'Provider Quota', subtitle: '', icon: 'tune-variant', section: 'OmniProxy', kind: 'collection', path: '/api/providers/quota-windows', page: '/dashboard/quota' },
  { id: 'quota-share', title: 'Quota Sharing', subtitle: '', icon: 'chart-pie', section: 'OmniProxy', kind: 'stats', path: '/api/quota/plans', page: '/dashboard/costs/quota-share' },
  { id: 'context-settings', title: 'Compression Settings', subtitle: 'Global defaults', icon: 'cog-outline', section: 'OmniProxy', kind: 'config', path: '/api/context/combos', method: 'post', page: '/dashboard/context/settings' },
  { id: 'context-combos', title: 'Engine Combos', subtitle: '', icon: 'layers-triple-outline', section: 'OmniProxy', kind: 'config', path: '/api/context/combos', method: 'post', page: '/dashboard/context/combos' },
  { id: 'context-caveman', title: 'Caveman', subtitle: 'Prompt compression', icon: 'account-voice', section: 'OmniProxy', kind: 'config', path: '/api/settings/compression', method: 'put', page: '/dashboard/context/caveman' },
  { id: 'context-rtk', title: 'RTK', subtitle: 'Output filtering', icon: 'filter-variant', section: 'OmniProxy', kind: 'config', path: '/api/context/rtk/filters', method: 'post', page: '/dashboard/context/rtk' },
  { id: 'context-headroom', title: 'Headroom', subtitle: 'Tabular compaction', icon: 'table-large', section: 'OmniProxy', kind: 'config', path: '/api/settings/compression', method: 'put', page: '/dashboard/context/headroom' },
  { id: 'context-session-dedup', title: 'Session Dedup', subtitle: 'Cross-turn deduplication', icon: 'merge', section: 'OmniProxy', kind: 'config', path: '/api/settings/compression', method: 'put', page: '/dashboard/context/session-dedup' },
  { id: 'context-ccr', title: 'CCR', subtitle: 'Retrieve markers', icon: 'magnify', section: 'OmniProxy', kind: 'config', path: '/api/settings/compression', method: 'put', page: '/dashboard/context/ccr' },
  { id: 'context-llmlingua', title: 'LLMLingua', subtitle: 'Semantic pruning', icon: 'scissors-cutting', section: 'OmniProxy', kind: 'config', path: '/api/settings/compression', method: 'put', page: '/dashboard/context/llmlingua' },
  { id: 'context-lite', title: 'Lite', subtitle: 'Fast whitespace cleanup', icon: 'feather', section: 'OmniProxy', kind: 'config', path: '/api/settings/compression', method: 'put', page: '/dashboard/context/lite' },
  { id: 'context-aggressive', title: 'Aggressive', subtitle: 'Summary + aging', icon: 'fire', section: 'OmniProxy', kind: 'config', path: '/api/settings/compression', method: 'put', page: '/dashboard/context/aggressive' },
  { id: 'context-ultra', title: 'Ultra', subtitle: 'Heuristic pruning', icon: 'lightning-bolt', section: 'OmniProxy', kind: 'config', path: '/api/settings/compression', method: 'put', page: '/dashboard/context/ultra' },
  { id: 'context-omniglyph', title: 'OmniGlyph', subtitle: 'Context-as-image', icon: 'image-outline', section: 'OmniProxy', kind: 'config', path: '/api/settings/compression', method: 'put', page: '/dashboard/context/omniglyph' },
  { id: 'compression-studio', title: 'Compression Studio', subtitle: 'Live engine cascade', icon: 'chart-line', section: 'OmniProxy', kind: 'config', path: '/api/settings/compression/rules', method: 'post', page: '/dashboard/compression/studio' },
  { id: 'compression-exclusions', title: 'Exclusions', subtitle: 'Per-model/endpoint bypass', icon: 'block-helper', section: 'OmniProxy', kind: 'config', path: '/api/settings/compression', method: 'put', page: '/dashboard/compression/exclusions' },
  { id: 'cli-code', title: 'CLI Code', subtitle: '', icon: 'console', section: 'OmniProxy', kind: 'config', path: '/api/cli-tools/claude-settings', method: 'post', page: '/dashboard/cli-code' },
  { id: 'cli-agents', title: 'CLI Agents', subtitle: '', icon: 'robot', section: 'OmniProxy', kind: 'collection', path: '/api/cli-tools/all-statuses', page: '/dashboard/cli-agents' },
  { id: 'acp-agents', title: 'ACP Agents', subtitle: '', icon: 'robot-outline', section: 'OmniProxy', kind: 'collection', path: '/api/acp/agents', page: '/dashboard/acp-agents' },
  { id: 'cloud-agents', title: 'Cloud Agents', subtitle: '', icon: 'cloud-outline', section: 'OmniProxy', kind: 'collection', path: '/api/v1/agents/tasks', page: '/dashboard/cloud-agents' },
  { id: 'conductor', title: 'Conductor', subtitle: 'CLI-agent fleet', icon: 'music', section: 'OmniProxy', kind: 'collection', path: '/api/conductor/fleet', page: '/dashboard/conductor' },
  { id: 'orchestration', title: 'Orchestration', subtitle: '', icon: 'swap-horizontal-bold', section: 'OmniProxy', kind: 'collection', path: '/api/conductor/fleet', page: '/dashboard/orchestration' },
  { id: 'agent-bridge', title: 'Agent Bridge', subtitle: '', icon: 'swap-horizontal-bold', section: 'OmniProxy', kind: 'collection', path: '/api/tools/agent-bridge/bypass', page: '/dashboard/tools/agent-bridge' },
  { id: 'traffic-inspector', title: 'Traffic Inspector', subtitle: '', icon: 'swap-horizontal-variant', section: 'OmniProxy', kind: 'collection', path: '/api/tools/traffic-inspector/hosts', page: '/dashboard/tools/traffic-inspector' },
  { id: 'discovery', title: 'Discovery', subtitle: '', icon: 'compass-outline', section: 'OmniProxy', kind: 'collection', path: '/api/discovery/results', page: '/dashboard/discovery' },
  { id: 'api-endpoints', title: 'API Endpoints', subtitle: '', icon: 'code-braces', section: 'OmniProxy', kind: 'collection', path: '/api/openapi/spec', page: '/dashboard/api-endpoints' },
  { id: 'webhooks', title: 'Webhooks', subtitle: 'Get notified of events', icon: 'web', section: 'OmniProxy', kind: 'collection', path: '/api/webhooks', page: '/dashboard/webhooks' },
  { id: 'log-export', title: 'Log Export', subtitle: 'Ship call logs out', icon: 'export-variant', section: 'OmniProxy', kind: 'collection', path: '/api/log-export/status', page: '/dashboard/log-export' },
  { id: 'proxy', title: 'Proxy', subtitle: '', icon: 'dns-outline', section: 'OmniProxy', kind: 'collection', path: '/api/v1/management/proxy-subscriptions', page: '/dashboard/system/proxy' },
  // ── Analytics ──
  { id: 'usage', title: 'Usage', subtitle: '', icon: 'chart-bar', section: 'Analytics', kind: 'stats', path: '/api/analytics/diversity', page: '/dashboard/analytics' },
  { id: 'combo-health', title: 'Combo Health', subtitle: '', icon: 'heart-pulse', section: 'Analytics', kind: 'stats', path: '/api/combos/metrics', page: '/dashboard/analytics/combo-health' },
  { id: 'utilization', title: 'Utilization', subtitle: '', icon: 'gauge', section: 'Analytics', kind: 'stats', path: '/api/usage/utilization', page: '/dashboard/analytics/utilization' },
  { id: 'cache', title: 'Cache', subtitle: '', icon: 'database-outline', section: 'Analytics', kind: 'config', path: '/api/cache', method: 'post', page: '/dashboard/cache' },
  { id: 'analytics-compression', title: 'Compression', subtitle: '', icon: 'chart-box-outline', section: 'Analytics', kind: 'config', path: '/api/analytics/compression', method: 'post', page: '/dashboard/analytics/compression' },
  { id: 'analytics-search', title: 'Search', subtitle: '', icon: 'magnify', section: 'Analytics', kind: 'stats', path: '/api/v1/search/analytics', page: '/dashboard/analytics/search' },
  { id: 'analytics-evals', title: 'Evals', subtitle: '', icon: 'flask-outline', section: 'Analytics', kind: 'stats', path: '/api/evals', page: '/dashboard/analytics/evals' },
  { id: 'provider-stats', title: 'Provider Stats', subtitle: '', icon: 'chart-donut', section: 'Analytics', kind: 'stats', path: '/api/provider-stats', page: '/dashboard/provider-stats' },
  { id: 'activity', title: 'Activity', subtitle: '', icon: 'timeline-clock-outline', section: 'Analytics', kind: 'stats', path: '/api/compliance/audit-log', page: '/dashboard/activity' },
  // ── Costs ──
  { id: 'costs-overview', title: 'Overview', subtitle: '', icon: 'wallet-outline', section: 'Costs', kind: 'stats', path: '/api/keys', page: '/dashboard/costs' },
  { id: 'costs-pricing', title: 'Pricing', subtitle: '', icon: 'tag-outline', section: 'Costs', kind: 'stats', path: '/api/pricing', page: '/dashboard/costs/pricing' },
  { id: 'costs-budget', title: 'Budget', subtitle: '', icon: 'piggy-bank-outline', section: 'Costs', kind: 'stats', path: '/api/usage/budget', page: '/dashboard/costs/budget' },
  { id: 'free-tiers', title: 'Free-Tier Budget', subtitle: '', icon: 'ticket-outline', section: 'Costs', kind: 'stats', path: '/api/free-tier/summary', page: '/dashboard/free-tiers' },
  { id: 'free-provider-rankings', title: 'Free Provider Rankings', subtitle: '', icon: 'trophy-outline', section: 'Costs', kind: 'stats', path: '/api/provider-models', page: '/dashboard/free-provider-rankings' },
  { id: 'radar', title: 'Radar Catalog', subtitle: '', icon: 'radar', section: 'Costs', kind: 'config', path: '/api/radar/settings', method: 'post', page: '/dashboard/radar' },
  // ── Monitoring ──
  { id: 'logs', title: 'Logs', subtitle: '', icon: 'file-document-outline', section: 'Monitoring', kind: 'custom', route: '/logs', page: '/dashboard/logs' },
  { id: 'logs-proxy', title: 'Proxy Logs', subtitle: '', icon: 'network-outline', section: 'Monitoring', kind: 'collection', path: '/api/provider-nodes', page: '/dashboard/logs/proxy' },
  { id: 'logs-console', title: 'Console Logs', subtitle: '', icon: 'console-line', section: 'Monitoring', kind: 'collection', path: '/api/logs/console', page: '/dashboard/logs/console' },
  { id: 'logs-timeline', title: 'Timeline', subtitle: '', icon: 'format-list-checks', section: 'Monitoring', kind: 'collection', path: '/api/resilience/model-cooldowns', page: '/dashboard/logs/timeline' },
  { id: 'conversations', title: 'Conversations', subtitle: '', icon: 'forum-outline', section: 'Monitoring', kind: 'collection', path: '/api/resilience/model-cooldowns', page: '/dashboard/conversations' },
  { id: 'audit', title: 'Audit Log', subtitle: '', icon: 'shield-check-outline', section: 'Monitoring', kind: 'collection', path: '/api/mcp/audit/stats', page: '/dashboard/audit' },
  { id: 'audit-mcp', title: 'MCP Audit', subtitle: '', icon: 'shield-account-outline', section: 'Monitoring', kind: 'collection', path: '/api/mcp/audit/stats', page: '/dashboard/audit/mcp' },
  { id: 'audit-a2a', title: 'A2A Audit', subtitle: '', icon: 'shield-link-variant-outline', section: 'Monitoring', kind: 'collection', path: '/api/a2a/tasks/history', page: '/dashboard/audit/a2a' },
  { id: 'health', title: 'Health', subtitle: '', icon: 'heart-outline', section: 'Monitoring', kind: 'stats', path: '/api/health', page: '/dashboard/health' },
  { id: 'runtime', title: 'Runtime', subtitle: '', icon: 'server', section: 'Monitoring', kind: 'collection', path: '/api/monitoring/health', page: '/dashboard/runtime' },
  { id: 'resilience', title: 'Resilience', subtitle: '', icon: 'web-refresh', section: 'Monitoring', kind: 'config', path: '/api/resilience/connections', method: 'post', page: '/dashboard/resilience/connections' },
  // ── Dev Tools ──
  { id: 'translator', title: 'Translator', subtitle: '', icon: 'translate', section: 'Dev Tools', kind: 'local', path: '/api/providers', note: 'An interactive text tool on the dashboard; its API takes text rather than returning a resource.', page: '/dashboard/translator' },
  { id: 'playground', title: 'Playground', subtitle: '', icon: 'toolbox-outline', section: 'Dev Tools', kind: 'custom', route: '/(tabs)/chat', page: '/dashboard/playground' },
  { id: 'search-tools', title: 'Search Tools', subtitle: '', icon: 'magnify-plus-outline', section: 'Dev Tools', kind: 'collection', path: '/api/search/providers', page: '/dashboard/search-tools' },
  // ── Agentic Features ──
  { id: 'memory', title: 'Memory', subtitle: '', icon: 'brain', section: 'Agentic Features', kind: 'collection', path: '/api/memory', page: '/dashboard/memory' },
  { id: 'agent-skills', title: 'AgentSkills', subtitle: '', icon: 'hand-back-right-outline', section: 'Agentic Features', kind: 'collection', path: '/api/agent-skills', page: '/dashboard/agent-skills' },
  { id: 'chaos', title: 'Chaos Mode', subtitle: 'Multi-model parallel execution', icon: 'swap-horizontal', section: 'Agentic Features', kind: 'config', path: '/api/chaos/config', method: 'put', page: '/dashboard/chaos' },
  { id: 'omni-skills', title: 'OmniSkills', subtitle: '', icon: 'magic-staff', section: 'Agentic Features', kind: 'config', path: '/api/settings', method: 'patch', page: '/dashboard/omni-skills' },
  { id: 'mcp', title: 'MCP Server', subtitle: '', icon: 'server-network', section: 'Agentic Features', kind: 'collection', path: '/api/mcp/status', page: '/dashboard/mcp' },
  { id: 'a2a', title: 'A2A Server', subtitle: '', icon: 'swap-horizontal-bold', section: 'Agentic Features', kind: 'collection', path: '/api/a2a/status', page: '/dashboard/a2a' },
  { id: 'plugins', title: 'Plugins', subtitle: '', icon: 'power-plug-outline', section: 'Agentic Features', kind: 'collection', path: '/api/plugins', page: '/dashboard/plugins' },
  // ── Other Features ──
  { id: 'leaderboard', title: 'Leaderboard', subtitle: '', icon: 'trophy-outline', section: 'Other Features', kind: 'config', path: '/api/settings', method: 'patch', page: '/dashboard/leaderboard' },
  { id: 'profile', title: 'Profile', subtitle: '', icon: 'account-outline', section: 'Other Features', kind: 'config', path: '/api/settings', method: 'patch', page: '/dashboard/profile' },
  { id: 'tokens', title: 'Tokens', subtitle: '', icon: 'ticket-confirmation-outline', section: 'Other Features', kind: 'config', path: '/api/settings', method: 'patch', page: '/dashboard/tokens' },
  { id: 'gamification-admin', title: 'Gamification Admin', subtitle: '', icon: 'account-cog-outline', section: 'Other Features', kind: 'collection', path: '/api/gamification/anomalies', page: '/dashboard/gamification/admin' },
  { id: 'media', title: 'Media', subtitle: '', icon: 'image-multiple-outline', section: 'Other Features', kind: 'config', path: '/api/providers', method: 'patch', page: '/dashboard/cache/media' },
  { id: 'batch', title: 'Batch Jobs', subtitle: '', icon: 'format-list-numbered', section: 'Other Features', kind: 'collection', path: '/api/providers', page: '/dashboard/batch' },
  { id: 'batch-files', title: 'Files', subtitle: '', icon: 'folder-outline', section: 'Other Features', kind: 'collection', path: '/api/v1/files', page: '/dashboard/batch/files' },
  // ── Configuration ──
  { id: 'settings-general', title: 'Storage', subtitle: '', icon: 'cog-outline', section: 'Configuration', kind: 'custom', route: '/settings', page: '/dashboard/settings/general' },
  { id: 'settings-appearance', title: 'Appearance', subtitle: '', icon: 'palette-outline', section: 'Configuration', kind: 'local', path: '/api/settings', note: 'The dashboard\'s own theme and layout. The phone app uses the system theme.', page: '/dashboard/settings/appearance' },
  { id: 'settings-ai', title: 'AI Settings', subtitle: '', icon: 'brain', section: 'Configuration', kind: 'config', path: '/api/settings', method: 'patch', page: '/dashboard/settings/ai' },
  { id: 'settings-modality-bridge', title: 'Modality Bridge', subtitle: '', icon: 'image-search-outline', section: 'Configuration', kind: 'config', path: '/api/modality-bridge/stats', method: 'post', page: '/dashboard/settings/modality-bridge' },
  { id: 'settings-routing', title: 'Global Routing', subtitle: '', icon: 'routes', section: 'Configuration', kind: 'config', path: '/api/settings', method: 'patch', page: '/dashboard/settings/routing' },
  { id: 'settings-resilience', title: 'Resilience', subtitle: '', icon: 'shield-outline', section: 'Configuration', kind: 'config', path: '/api/resilience', method: 'patch', page: '/dashboard/settings/resilience' },
  { id: 'settings-advanced', title: 'Advanced', subtitle: '', icon: 'cog-outline', section: 'Configuration', kind: 'config', path: '/api/settings', method: 'patch', page: '/dashboard/settings/advanced' },
  { id: 'settings-security', title: 'Security', subtitle: '', icon: 'lock-outline', section: 'Configuration', kind: 'config', path: '/api/settings', method: 'patch', page: '/dashboard/settings/security' },
  { id: 'settings-access-tokens', title: 'Access Tokens', subtitle: '', icon: 'key-variant', section: 'Configuration', kind: 'config', path: '/api/cli/tokens', method: 'post', page: '/dashboard/settings/access-tokens' },
  { id: 'settings-feature-flags', title: 'Feature Flags', subtitle: '', icon: 'flag-variant-outline', section: 'Configuration', kind: 'config', path: '/api/settings/feature-flags', method: 'put', page: '/dashboard/settings/feature-flags' },
  { id: 'settings-cache', title: 'Cache', subtitle: '', icon: 'database-outline', section: 'Configuration', kind: 'config', path: '/api/cache', method: 'post', page: '/dashboard/settings/cache' },
  { id: 'settings-sidebar', title: 'Sidebar', subtitle: '', icon: 'menu', section: 'Configuration', kind: 'local', path: '/api/settings', note: 'Which items the browser dashboard shows in its sidebar. The app has its own catalog.', page: '/dashboard/settings/sidebar' },
  // ── Help ──
  { id: 'docs', title: 'Docs', subtitle: '', icon: 'book-open-page-variant-outline', section: 'Help', kind: 'local', note: 'The dashboard renders its own documentation as pages inside the browser. There is no gateway API behind it, and the app has no documentation site to open — so this says so instead of pretending to.', page: '/docs' },
  { id: 'issues', title: 'Issues', subtitle: '', icon: 'bug-outline', section: 'Help', kind: 'external', page: 'https://github.com/diegosouzapw/OmniRoute/issues' },
  { id: 'changelog', title: 'Changelog', subtitle: '', icon: 'calendar-clock-outline', section: 'Help', kind: 'local', path: '/api/settings', note: 'Release notes are published with the project.', page: '/dashboard/changelog' },
];

/** Dashboard section order, so the app's catalog reads like the web sidebar. */
const SECTION_ORDER = ["OmniProxy","Analytics","Costs","Monitoring","Dev Tools","Agentic Features","Other Features","Configuration","Help"];

const SECTION_ICONS: Record<string, Surface['icon']> = {
  'OmniProxy': 'swap-horizontal-bold',
  'Analytics': 'chart-box-outline',
  'Costs': 'cash-multiple',
  'Monitoring': 'monitor-dashboard',
  'Dev Tools': 'toolbox-outline',
  'Agentic Features': 'robot-outline',
  'Other Features': 'shape-outline',
  'Configuration': 'tune-variant',
  'Help': 'help-circle-outline',
};

const SECTION_PRESENTATION: Record<string, { label: string; subtitle: string }> = {
  'OmniProxy': { label: 'Gateway', subtitle: 'Endpoints, API keys, providers and combos' },
  'Analytics': { label: 'Analytics', subtitle: 'Usage, health, evaluations and search' },
  'Costs': { label: 'Costs', subtitle: 'Spend, pricing, budgets and free tiers' },
  'Monitoring': { label: 'Monitoring', subtitle: 'Logs, activity and runtime health' },
  'Dev Tools': { label: 'Developer tools', subtitle: 'CLI tools, agent bridge and traffic inspection' },
  'Agentic Features': { label: 'Agents', subtitle: 'Cloud agents, skills and memory' },
  'Other Features': { label: 'More features', subtitle: 'Everything else the gateway offers' },
  'Configuration': { label: 'Settings', subtitle: 'Compression, routing, cache and security' },
  'Help': { label: 'Help & about', subtitle: 'Docs, changelog and this build' },
};

export const SECTIONS: SurfaceSection[] = SECTION_ORDER.map((title) => ({
  id: title.toLowerCase().replace(/[^a-z0-9]+/g, '-'),
  title,
  label: SECTION_PRESENTATION[title]?.label ?? title,
  subtitle: SECTION_PRESENTATION[title]?.subtitle ?? '',
  icon: SECTION_ICONS[title] ?? 'folder-outline',
  surfaces: SURFACES.filter((surface) => surface.section === title),
})).filter((section) => section.surfaces.length > 0);

export function findSurface(id: string): Surface | undefined {
  return SURFACES.find((surface) => surface.id === id);
}

/** Search across title, subtitle, section and the API path it uses. */
export function searchSurfaces(query: string): Surface[] {
  const needle = query.trim().toLowerCase();
  if (!needle) return SURFACES;
  return SURFACES.filter((surface) =>
    [surface.title, surface.subtitle, surface.section, surface.id, surface.path ?? '']
      .join(' ')
      .toLowerCase()
      .includes(needle)
  );
}
